#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Путь к .git
export HUSKY_GIT_PARAMS="$PWD/../.git"

# Переходим в папку frontend
cd frontend

npm run build
npm run lint:ts
npm run lint:scss
npm run test:unit
npm run storybook:build